#!/usr/bin/env python3
"""
Evaluate automatic front foot strike detection against manual labels.

This script runs analyze_pitch_timing.py for a small labeled set WITHOUT passing
manual --front-foot-strike-frame, then compares the automatic front foot strike
frame to the manually labeled ground truth.

No cloud API is used. No API key is required.
"""

import csv
import json
import statistics
import subprocess
import sys
from pathlib import Path


OUTPUTS_DIR = Path("outputs")
EVALUATION_CSV_PATH = OUTPUTS_DIR / "front_foot_strike_evaluation.csv"

LABELED_PITCHES = [
    {
        "pitch_id": "pitch_01",
        "video": "videos/IMG_1322.MOV",
        "start_time": 26,
        "end_time": 28,
        "manual_ffs_frame": 1618,
        "output_prefix": "eval_pitch_01_auto",
    },
    {
        "pitch_id": "pitch_02",
        "video": "videos/IMG_1322.MOV",
        "start_time": 36,
        "end_time": 38,
        "manual_ffs_frame": 2204,
        "output_prefix": "eval_pitch_02_auto",
    },
    {
        "pitch_id": "pitch_03",
        "video": "videos/IMG_1322.MOV",
        "start_time": 46,
        "end_time": 48,
        "manual_ffs_frame": 2851,
        "output_prefix": "eval_pitch_03_auto",
    },
]


CSV_FIELDS = [
    "pitch_id",
    "manual_ffs_frame",
    "auto_ffs_frame",
    "frame_error",
    "absolute_frame_error",
    "time_error_ms",
    "front_foot_strike_confidence",
    "sequence_result",
    "front_foot_strike_debug_reason",
]


def run_analyzer_for_pitch(pitch):
    """Run analyze_pitch_timing.py for one labeled pitch using auto FFS only."""
    command = [
        sys.executable,
        "analyze_pitch_timing.py",
        pitch["video"],
        "--throwing-hand",
        "right",
        "--start-time",
        str(pitch["start_time"]),
        "--end-time",
        str(pitch["end_time"]),
        "--pelvis-peak-search-end-ms",
        "250",
        "--trunk-peak-search-end-ms",
        "300",
        "--output-prefix",
        pitch["output_prefix"],
        "--export-event-review",
    ]

    print(f"Running auto analysis for {pitch['pitch_id']}...")
    subprocess.run(command, check=True)


def load_timing_report(output_prefix):
    """Load the timing report generated by analyze_pitch_timing.py."""
    report_path = OUTPUTS_DIR / f"{output_prefix}_timing_report.json"
    with report_path.open("r", encoding="utf-8") as f:
        return json.load(f)


def evaluate_pitch(pitch):
    """Run analysis for one pitch and return a CSV-ready evaluation row."""
    run_analyzer_for_pitch(pitch)
    report = load_timing_report(pitch["output_prefix"])

    manual_frame = pitch["manual_ffs_frame"]
    auto_frame = report.get("front_foot_strike_frame")
    fps = report.get("fps")

    if auto_frame is None:
        frame_error = None
        absolute_frame_error = None
        time_error_ms = None
    else:
        frame_error = int(auto_frame) - int(manual_frame)
        absolute_frame_error = abs(frame_error)
        time_error_ms = (frame_error / fps) * 1000.0 if fps else None

    return {
        "pitch_id": pitch["pitch_id"],
        "manual_ffs_frame": manual_frame,
        "auto_ffs_frame": auto_frame,
        "frame_error": frame_error,
        "absolute_frame_error": absolute_frame_error,
        "time_error_ms": time_error_ms,
        "front_foot_strike_confidence": report.get("front_foot_strike_confidence"),
        "sequence_result": report.get("sequence_result"),
        "front_foot_strike_debug_reason": report.get("front_foot_strike_debug_reason"),
    }


def write_evaluation_csv(rows):
    """Save evaluation rows to outputs/front_foot_strike_evaluation.csv."""
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    with EVALUATION_CSV_PATH.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def print_summary(rows):
    """Print simple aggregate evaluation metrics."""
    absolute_errors = [
        row["absolute_frame_error"]
        for row in rows
        if row["absolute_frame_error"] is not None
    ]

    print(f"Pitches evaluated: {len(rows)}")

    if not absolute_errors:
        print("Mean absolute frame error: n/a")
        print("Median absolute frame error: n/a")
        print("Max absolute frame error: n/a")
        print("Pitches within 3 frames: 0")
        print("Pitches within 5 frames: 0")
        print(f"Saved evaluation CSV: {EVALUATION_CSV_PATH}")
        return

    print(f"Mean absolute frame error: {statistics.mean(absolute_errors):.2f}")
    print(f"Median absolute frame error: {statistics.median(absolute_errors):.2f}")
    print(f"Max absolute frame error: {max(absolute_errors)}")
    print(f"Pitches within 3 frames: {sum(error <= 3 for error in absolute_errors)}")
    print(f"Pitches within 5 frames: {sum(error <= 5 for error in absolute_errors)}")
    print(f"Saved evaluation CSV: {EVALUATION_CSV_PATH}")


def main():
    """Evaluate all labeled pitches."""
    rows = [evaluate_pitch(pitch) for pitch in LABELED_PITCHES]
    write_evaluation_csv(rows)
    print_summary(rows)


if __name__ == "__main__":
    main()
